version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:8.4.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install module
          command: npm install
      - run:
          name: build
          command: npm run build:production
      - run:
          name: package
          command: npm run package
      - run:
          name: status
          command: git status
      - store_artifacts:
          path: dist
          destination: binary
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules